### ISSUE TITLE
Support multiple projects

### ISSUE THREAD

**Issue by pleonex** [amitab/atom-cscope#12]
In Atom I usually have several projects open at once (you can add a new project from the TreeView with mouse right button -> Add Project Folder). In that case, the plugin selects only one project to work with (in my case it selects a nodejs project ~~so it's causing probably #11~~). It would be so useful to be able to select the project I would like to use, maybe as a dropdown box in the plugin or as a configuration.

Thanks for the plugin!

**Comment by amitab** [comment]
I had not considered using multiple projects. Seems like a good idea. Ill plan it out for the next minor release.

**Comment by amitab** [comment]
Fixed in master c1b15b9bfd50c0e5063934f54ba3ddaad6ba7018
