### ISSUE TITLE
Win32 - "Failed to spawn command find. Make sure find is installed and on your PATH"

### ISSUE THREAD

**Issue by stephen-d-hill** [amitab/atom-cscope#17]
I'm really struggling to get this plugin to work on Windows.
I have a native UNIX find.exe (that isn't bound to CygWin), but I can't figure out where this plugin wants find.exe to be......

**Comment by amitab** [comment]
I will be removing dependency on find soon, and I will be using node.js to find the files instead. So as long as you have cscope installed, it should work :)

**Comment by amitab** [comment]
@stephen-d-hill Can you try using the issue#17 branch of this repository to test whether it works on your system? I just tried it with Windows 7 and it is working. 
Also, this is the first time I am using this package on Windows (didn't intend it to be used on windows while I was developing it). I am using cscope 5.17a win32 port, and I am unable to use the -q option to generate inverted index files. Are you able to use it?

**Comment by stephen-d-hill** [comment]
I am using v15.8a of cscope.exe.
Can you tell me:
- Path of find.exe.
- Path of cscope.exe.
- Your PATH environment setting.

**Comment by stephen-d-hill** [comment]
Downloaded issue-17. Unzipped to packages dir.
Uninstalled atom-cscope.
Ran 

```
C:\Users\SHill\AppData\Local\atom\packages\atom-cscope-issue-17>apm link
INFO: Could not find files for the given pattern(s).
The system cannot find the file specified.
C:\Users\SHill\.atom\packages\atom-cscope -> C:\Users\SHill\AppData\Local\atom\p
ackages\atom-cscope-issue-17
```

But now it won't do anything, and the package manager can't see it either, although it appears in the package menu.

**Comment by stephen-d-hill** [comment]
Ah I need to run:

`apm install`

Now everything works!

**Comment by stephen-d-hill** [comment]
I said everything is working, which isn't quite correct.
The path to cscope.exe setting does NOT work.
I have to copy cscope.exe into my project root folder for it to work.

**Comment by stephen-d-hill** [comment]
Ugh, I spoke too soon. It worked once, but now has stopped working!

**Comment by stephen-d-hill** [comment]
If I delete cscope.files & cscope.out then I can refresh, but only then :(.
And I still have to have cscope.exe in the project root folder :(

**Comment by amitab** [comment]
Package now uses `dir` command of windows, so this shouldn't be an issue anymore
