### ISSUE TITLE
wrong system header path?

### ISSUE THREAD

**Issue by pangqingyuan1991** [amitab/atom-cscope#18]
when I search a function which is in /usr/include/xxx.h and click the search result, atom will open 
$PROJECT/usr/include/xxx.h , a empty file.
Here $PROJECT is my project dir.

**Comment by amitab** [comment]
Hi, sorry for replying so late. I was swamped with work at office.
This shouldnt be happening. I've checked it in 1778c98e7a76810401206b1603e84529386c5149 it was changed to work with absolute paths and relative ones and it seems to be working fine. Can you check if the changes in this commit is present in your installation? 

If it is, can you go to ~/.atom/packages/atom-cscope/lib/models/result-model.coffee:12
and in the method `getFilePath` just add this line under the assignment of `filePath`:

    getFilePath: ->
      filePath = if @fileName.startsWith('/') then @fileName else path.join(@cwd, @fileName)
      console.log filePath # add this line
      return filePath

And before running, press Ctrl+Shift+I and go to console and check the output. Just need to see if this is still a problem.

**Comment by amitab** [comment]
My bad. Seems like it was not in any of the releases. Please install 0.15.0.
Fixed in 1778c98e7a76810401206b1603e84529386c5149
