### ISSUE TITLE
Doesn't seem to work on OS X

### ISSUE THREAD

**Issue by royger** [amitab/atom-cscope#22]
Hello,

Thanks for doing this cscope plug-in! I'm having some issues trying to use it, first it doesn't seem to be able to generate/update the database, I just get an error message but no log in the console at all. I've built the database myself, but then search doesn't seem to work either, and I get the following messages on the console:

/Users/royger/.atom/packages/atom-cscope/lib/atom-cscope.coffee:90 Uncaught (in promise) TypeError: Cannot read property 'indexOf' of undefined
    at /Users/royger/.atom/packages/atom-cscope/lib/atom-cscope.coffee:73:24
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by amitab** [comment]
I don't have a mac, but let me try setting up a VM to check whats going on :)

**Comment by amitab** [comment]
Ive almost re-written everything! Please try v1.0.0 release and check if this issue still persists. I'll keep this opened just incase.

**Comment by royger** [comment]
Oh, I no longer use atom, sorry.

**Comment by amitab** [comment]
Neither do I! I use vim mostly, which is why I was so slow on handling these open issues. Issue closed then :)
