### ISSUE TITLE
"Error: Unable to refresh cscope database"

### ISSUE THREAD

**Issue by fadeevab** [amitab/atom-cscope#23]
It happens if some header or C file is a symbols link (it's wrong approach, but unfortunately I have such project).

**Fix**: improve your default "find" command to the next one:

`find . \( -name "*.c" -o -name "*.cpp" -o -name "*.h" -o -name "*.hpp" \) -type f > cscope.files`

This command excludes symlinks. I'm not an active github user, so it will be grate if you make a fix.

Thank you!

**Comment by fadeevab** [comment]
Ok, I created a pull request for you.

**Comment by amitab** [comment]
Merged :)
