### ISSUE TITLE
Dies in an exception handler

### ISSUE THREAD

**Issue by savannidgerinel** [amitab/atom-cscope#25]
The cscope plugin is throwing an exception in a promise, and then failing to handle the exception correctly.

The error:

```
atom-cscope.coffee:73 Uncaught (in promise) TypeError: Cannot read property 'indexOf' of undefined(…
  (anonymous function) @ atom-cscope.coffee:73
  _tickCallback @ internal/process/next_tick.js:103
```

It appears to be in this block of code:

```
      cscope.runCscopeCommands option, keyword, projects
      .then (data) =>
        @atomCscopeView.clearItems()
        @atomCscopeView.applyResultSet(data)
      .catch (data) =>
        if data.message.indexOf("cannot open file cscope.out") > 0
          notifier.addError "Error: Please generate the cscope database."
        else
          notifier.addError "Error: " + data.message
```

Specifically, the line hilighted is the line `if data.message.indexOf...`

For my description "project" refers to the atom concept of a project. I have a dozen directories added to the project. I am running the search from a panel in which I have opened a file in one of those directories. The base of the directory containing that file contains `cscope.out` and `cscope.files`.

**Comment by amitab** [comment]
I will have to try and change the structure of how the exceptions are allowed to bubble out. Hopefully Ill have this done soon :)

**Comment by amitab** [comment]
Ive almost re-written everything! Please try v1.0.0 release and check if this issue still persists. I'll keep this opened just incase.
