### ISSUE TITLE
Object.add is deprecated.

### ISSUE THREAD

**Issue by sungyeon** [amitab/atom-cscope#26]
Are you trying to listen for the 'core:confirm' Atom command with `jQuery::on`?
`jQuery::trigger` can no longer be used to listen for Atom commands. Please
use `atom.commands.add` instead. See the docs at
https://atom.io/docs/api/latest/CommandRegistry

**Comment by amitab** [comment]
Ill soon be removing JQuery completely and moving on to HTML5. Hopefully I can figure out how to use one of the frameworks mentioned here :) : https://github.com/atom/atom/issues/5756

**Comment by amitab** [comment]
Ive almost re-written everything! Please try v1.0.0 release and check if this issue still persists. I'll keep this opened just incase.
