### ISSUE TITLE
what is the -4058 issue??

### ISSUE THREAD

**Issue by guidol** [amitab/atom-cscope#28]
I installed and I make a cscope.out manually using my cygwin terminal.

but when I run the cscope, it returns -4058 error.

what should I do? I have to make the cscope.out with windows version of cscope?

**Comment by cherojeong** [comment]
Yes you have to make the cscope.out file with windows version of cscope as below
#cscope -q -R -b -i cscope.files

Also cscope execution file should be put it into folder in the PATH environment.
You can find it what I use as below link

https://code.google.com/archive/p/cscope-win32/downloads

**Comment by amitab** [comment]
Fixed in commit bed29e2d639037aab41e76b441260de5c312aa85
