### ISSUE TITLE
Uncaught Error executing command cscope [-dL0,V] Error: spawn cscope ENOENT

### ISSUE THREAD

**Issue by TiredMir** [amitab/atom-cscope#35]
Still having a problem with this:
[Enter steps to reproduce:]

1. Search
2. Good luck

**Atom**: 1.38.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-cscope](https://github.com/amitab/atom-cscope) package 1.1.0

### Stack Trace

Uncaught Error executing command cscope [-dL0,V] Error: spawn cscope ENOENT

```
At C:\Users\Mir\.atom\packages\atom-cscope\dist\cscope.js:114

undefined
```

### Commands

```
  2x -4:23.3.0 atom-cscope:toggle (div.tool-panel.tree-view)
     -3:08.4.0 command-palette:toggle (input.hidden-input)
     -2:50.8.0 editor:consolidate-selections (input.hidden-input)
     -2:50.8.0 core:cancel (input.hidden-input)
     -2:49.9.0 settings-view:open (input.hidden-input)
  2x -2:28.6.0 core:backspace (input.hidden-input)
     -1:47 atom-cscope:toggle (input.hidden-input)
  2x -1:44.1.0 core:backspace (input.hidden-input)
     -1:42.2.0 core:select-all (input.hidden-input)
     -1:42.1.0 editor:delete-to-beginning-of-word (input.hidden-input)
```

### Non-Core Packages

```
atom-cscope 1.1.0 
gpp-compiler 3.0.7 
language-x86-64-assembly 2.2.11 
```

**Comment by amitab** [comment]
Hi @TiredMir, thanks for reporting this issue!
Is the cscope executable in PATH? If not, have you added the path to cscope executable in the atom-cscope configuration?

**Comment by TiredMir** [comment]
Yes but there was a path collision on my part. Thank you for your help.
