### ISSUE TITLE
Can't scroll search results anymore

### ISSUE THREAD

**Issue by kjokinie** [amitab/atom-cscope#36]
Just updated to 1.1.0 version. The search results cannot be scrolled up and down anymore like in previous version. I cannot get a focus on the results widget in any way to move the results around, can only click on the lines to bring up the code. This is problematic when looking for something that has many hits (like function pointers assigned in various places), those just don't fit in the few lines that are visible.

The scrollbar is kind of visible on right, but it's just empty white bar, with no scroll location indicator there.

Used the plugin on Linux (Ubuntu 18.04) + Atom version 1.51.0 (x64).

**Comment by amitab** [comment]
Sorry about that, should be fixed now.

**Comment by kjokinie** [comment]
It works again. Big thanks!
