### ISSUE TITLE
Support for cscope program to be in location not in PATH

### ISSUE THREAD

**Issue by vishalpatel** [amitab/atom-cscope#9]
I find that on my system cscope is located in ~/editortools and everytime I invoke cscope I get nasty warning that 'cscope' is not in PATH. 

I double checked that ~/editortools is part of my $PATH variable but Atom's invocation has weird behavior if opened by "double clicking" App or when launched from cmd line as "atom myfile.c"

So I ended up changing the coffeescript and I've attached a diff that adds a config option and allows user to change its location.

Can you please apply this diff?
[cscope_binary_path_config.diff.txt](https://github.com/amitab/atom-cscope/files/119661/cscope_binary_path_config.diff.txt)

**Comment by amitab** [comment]
@vishalpatel Hey thanks for the patch! If you are ok with it, can you send in a pull request? If not I will apply the patch, but it would be nice to have a pull request :)

**Comment by vishalpatel** [comment]
I created a pull request

Hope it works out. 
-Vishal
